image: ghcr.io/cirruslabs/flutter:stable

variables:
  # Remplacez par le nom de votre dossier si nécessaire
  FLUTTER_PROJECT_DIR: "flutter_application_1"
  PUB_CACHE: "$CI_PROJECT_DIR/.pub-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - bin/cache/

stages:
  - analyze
  - build

before_script:
  - cd $FLUTTER_PROJECT_DIR
  - export PATH="$PATH:$HOME/.pub-cache/bin"
  # On force le rafraîchissement des dépendances au cas où
  - flutter pub get

# Étape 1 : Analyse (ne bloque plus le pipeline s'il y a des infos/warnings)
lint:
  stage: analyze
  script:
    - flutter analyze --no-fatal-infos --no-fatal-warnings
  allow_failure: true

# Étape 2 : Build de l'APK (C'est cette étape qui vous intéresse)
build_android:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    name: "Application_Android"
    paths:
      - $FLUTTER_PROJECT_DIR/build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"