pages:
  stage: deploy
  dependencies:
    - build_web # Optionnel : si vous avez un job de build séparé
  script:
    # 1. On build l'application pour le web
    # Remplacez /nom-du-projet/ par le nom de votre dépôt GitLab (important pour les liens)
    - flutter build web --release --base-href "/votre-nom-depot/"
    
    # 2. On crée le dossier public requis par GitLab
    - rm -rf public
    - mkdir public
    
    # 3. On déplace le résultat du build vers le dossier public
    - cp -r build/web/* public/
  artifacts:
    paths:
      - public # Obligatoire
  only:
    - master # On ne déploie que depuis la branche principale