image: ghcr.io/cirruslabs/flutter:stable

pages:
  stage: deploy
  script:
    - cd flutter_application_1
    - flutter pub get
    - flutter build web --release
    - cd ..
    - rm -rf public
    - mkdir public
    - cp -r flutter_application_1/build/web/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
